"""init

Revision ID: ca2fb14f6e67
Revises: e00e72623cc7
Create Date: 2025-02-11 20:21:39.041976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2fb14f6e67'
down_revision = 'e00e72623cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frameworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download', sa.String(length=255), nullable=False))
        batch_op.drop_column('download_link')

    with op.batch_alter_table('langs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download', sa.String(length=255), nullable=False))
        batch_op.drop_column('download_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('langs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download_link', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('download')

    with op.batch_alter_table('frameworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download_link', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('download')

    # ### end Alembic commands ###
